# -*- coding: utf-8 -*-
"""Figure5_PartA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OTPcGVZCWbCRpgrLtHwcDJ90QwvS4mVk
"""

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Patch #Line2D, which created legend in colored graphs, does not have a hatch option
from google.colab import drive
from google.colab import files
import os
drive.mount('/content/drive/')
csv = pd.read_csv('/content/drive/My Drive/Ground_Truth_Data.csv')

df = csv.copy()
print(df)

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# # Define the data as a dictionary
# data = {
#     'Behavior': ['Paired Exploration', 'Paired Exploration', 'Paired Exploration', 'Paired Exploration', 'Paired Exploration', 'Paired Exploration', 'Paired Exploration', 'Paired Exploration',
#                  'Pursuit', 'Pursuit', 'Pursuit', 'Pursuit', 'Pursuit', 'Pursuit', 'Pursuit', 'Pursuit',
#                  'Anogenital Sniffing', 'Anogenital Sniffing', 'Anogenital Sniffing', 'Anogenital Sniffing', 'Anogenital Sniffing', 'Anogenital Sniffing', 'Anogenital Sniffing', 'Anogenital Sniffing',
#                  'Nose Nose', 'Nose Nose', 'Nose Nose', 'Nose Nose', 'Nose Nose', 'Nose Nose', 'Nose Nose', 'Nose Nose'],
#     'Method': ['SimBA', 'SimBA', 'SimBA', 'SimBA', 'Manual', 'Manual', 'Manual', 'Manual',
#                'SimBA', 'SimBA', 'SimBA', 'SimBA', 'Manual', 'Manual', 'Manual', 'Manual',
#                'SimBA', 'SimBA', 'SimBA', 'SimBA', 'Manual', 'Manual', 'Manual', 'Manual',
#                'SimBA', 'SimBA', 'SimBA', 'SimBA', 'Manual', 'Manual', 'Manual', 'Manual'],
#     'Bouts': [29, 21, 30, 20, 28, 23, 28, 26,
#               23, 13, 38, 19, 17, 12, 10, 9,
#               8, 5, 1, 4, 9, 5, 4, 4,
#               39, 27, 18, 16, 33, 17, 14, 18]
# }

# # Create the DataFrame
# df = pd.DataFrame(data)

# Calculate means and standard deviations
means = df.groupby(['Behavior', 'Method'])['Bouts'].mean().reset_index()
stds = df.groupby(['Behavior', 'Method'])['Bouts'].std().reset_index()

# Set the figure size
plt.figure(figsize=(12, 8))

# Create the bar plot
barplot = sns.barplot(x='Behavior', y='Bouts', hue='Method', data=means, palette=['antiquewhite', 'slategray'], ci=None)

# Overlay the individual data points
sns.stripplot(x='Behavior', y='Bouts', hue='Method', data=df, dodge=True, palette='dark:black', alpha=0.8, zorder=1, legend=False)

# Customize the plot
plt.xlabel('')
plt.ylabel('Bouts')
plt.title('')
plt.ylim(0, 40)

# Add error bars to each individual bar
for i in range(len(means)):
    behavior = means['Behavior'][i]
    method = means['Method'][i]
    mean_val = means['Bouts'][i]
    std_val = stds[(stds['Behavior'] == behavior) & (stds['Method'] == method)]['Bouts'].values[0]
    barplot.errorbar(x=i // 2 + i % 2 * 0.4 - 0.2, y=mean_val, yerr=std_val, fmt='none', c='black', capsize=5, label='Standard Deviation')

# Remove top and right spines
sns.despine()

# Save file as a PDF to Donwloads folder on Mac
file_path = "/content/SimbaGroundTruth.pdf"
plt.savefig(file_path)
files.download(file_path)

# Show the plot
plt.show()